-- Copy and paste this into your Supabase SQL Editor to set up the database

-- 1. Create the 'users' table
CREATE TABLE IF NOT EXISTS users (
  id bigint generated by default as identity primary key,
  user_id text not null unique,
  password text not null, -- In a real app, this should be hashed!
  role text not null check (role in ('cleaner', 'driver')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create the 'locations' table
CREATE TABLE IF NOT EXISTS locations (
  id bigint generated by default as identity primary key,
  address text not null,
  pincode text not null,
  city text not null,
  latitude text not null,
  longitude text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Insert default users (These are your login credentials!)
-- You can change the passwords here before running, or add more users.

-- Driver credentials: User ID: "driver1", Password: "driver123"
INSERT INTO users (user_id, password, role)
VALUES ('driver1', 'driver123', 'driver');

-- Cleaner credentials: User ID: "cleaner1", Password: "cleaner123"
INSERT INTO users (user_id, password, role)
VALUES ('cleaner1', 'cleaner123', 'cleaner');
