-- Copy and paste this into your Supabase SQL Editor to set up the database

-- 1. Create or Update the 'users' table (without the constraint first)
CREATE TABLE IF NOT EXISTS users (
  id bigint generated by default as identity primary key,
  user_id text not null unique,
  password text not null, -- In a real app, this should be hashed!
  role text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Safely drop the old check constraint if it exists
ALTER TABLE IF EXISTS users DROP CONSTRAINT IF EXISTS users_role_check;

-- 3. Update existing roles (migration for existing DBs)
UPDATE users SET role = 'admin' WHERE role = 'cleaner';

-- 4. Re-add the updated constraint
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role in ('admin', 'driver', 'user'));

-- 2. Create the 'locations' table
CREATE TABLE IF NOT EXISTS locations (
  id bigint generated by default as identity primary key,
  address text not null,
  pincode text not null,
  city text not null,
  latitude text not null,
  longitude text not null,
  assigned_driver text, -- To track which driver accepted the location
  status text default 'pending', -- 'pending' or 'collected'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Note: If locations table already exists, run this to add the new columns:
-- ALTER TABLE locations ADD COLUMN IF NOT EXISTS assigned_driver text;
-- ALTER TABLE locations ADD COLUMN IF NOT EXISTS status text default 'pending';
-- UPDATE locations SET status = 'pending' WHERE status IS NULL;

-- 3. Create the 'complaints' table
CREATE TABLE IF NOT EXISTS complaints (
  id bigint generated by default as identity primary key,
  user_id text not null,
  user_details text not null,
  bin_location text not null,
  description text not null,
  status text not null default 'pending',
  latitude text,
  longitude text,
  image_data text,
  assigned_driver text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Note: If complaints table already exists, run these to add the new columns:
-- ALTER TABLE complaints ADD COLUMN IF NOT EXISTS latitude text;
-- ALTER TABLE complaints ADD COLUMN IF NOT EXISTS longitude text;
-- ALTER TABLE complaints ADD COLUMN IF NOT EXISTS image_data text;
-- ALTER TABLE complaints ADD COLUMN IF NOT EXISTS assigned_driver text;

-- 4. Insert default users (These are your login credentials!)
-- Adding ON CONFLICT so it doesn't throw Duplicate Key errors on re-run

-- Driver credentials: User ID: "driver1", Password: "driver123"
INSERT INTO users (user_id, password, role)
VALUES ('driver1', 'driver123', 'driver')
ON CONFLICT (user_id) DO NOTHING;

-- Admin credentials: User ID: "admin1", Password: "admin123"
INSERT INTO users (user_id, password, role)
VALUES ('admin1', 'admin123', 'admin')
ON CONFLICT (user_id) DO NOTHING;
